/* eslint-disable */
// @ts-nocheck
// oxlint-disable
// ------
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DemoGroup: typeof import('./src/components/demo-group/demo-group.vue')['default']
    DemoGroupItem: typeof import('./src/components/demo-group-item/demo-group-item.vue')['default']
    PageWraper: typeof import('./src/components/page-wraper/page-wraper.vue')['default']
  }
}
